apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: ecommerce
    tier: frontend
    environment: production
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sleep', '3600']

---
apiVersion: v1
kind: Pod
metadata: 
  name: backend-pod
  labels:
    app: ecommerce
    tier: backend
    environment: production
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sleep', '3600']

---
apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: ecommerce
    tier: database
    environment: development
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sleep', '3600']