apiVersion: apps/v1
kind: Deployment
metadata: 
  name: session-app
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: session-app
  template:
    metadata: 
      labels: 
        app: session-app
    spec:
      containers:
        - name: app
          image: nginx:alpine
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata: 
  name: session-service
spec:
  selector:
    app: session-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP