apiVersion: v1
kind: Pod
metadata:
  name: simple-health-app
  labels:
    app: health-demo
spec: 
  containers:
    - name: webapp
      image: python:3.12-alpine
      command: ["python", "app/app.py"]
      ports:
        - containerPort: 8081
      livenessProbe:
        httpGet:
          path: /health
          port: 8081
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3
        timeoutSeconds: 2
      readinessProbe:
        httpGet:
          path: /ready
          port: 8081
        initialDelaySeconds: 5
        periodSeconds: 3
        failureThreshold: 2
        timeoutSeconds: 1

      volumeMounts:
        - name: app-code
          mountPath: /app

  volumes:
    - name: app-code
      configMap:
        name: health-app-config