apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-agent
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-agent-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: monitoring-agent
type: kubernetes.io/serice-account-token

