apiVersion: v1
kind: Pod
metadata: 
  name: test-rbac
spec:
  serviceAccountName: monitoring-agent
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["sleep"]
      args: ["3600"]