apiVersion: v1
kind: Service
metadata: 
  name: app-test-clusterip
  labels:
    app: app-test
spec:
  selector:
    app: app-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP