apiVersion: v1
kind: Service
metadata:
  name: app-test-nodeport
  labels:
    app: app-test
spec:
  selector:
    app: app-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort