apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: test-container
      image: busybox:latest
      command: ['sh', '-c', 'echo "Username: $USERNAME, Password: $PASSWORD" && sleep 3600']
      env:
        - name: USERNAME
          valueFrom:  
            secretKeyRef:
              name: mon-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mon-secret
              key: password
  restartPolicy: Never