apiVersion: v1
kind: Namespace
metadata:
  name: microvervices-app
  labels:
    name: microservices-app

---
apiVersion: v1
kind: Namespace
metadata: 
  name: monitoring
  labels:
    name: monitoring
