apiVersion: v1
kind: Pod
metadata:
  name: attacker
  namespace: default
  labels:
    app: attacker
spec:
  containers:
    - name: attacker
      image: curlimages/curl:8.10.1
      command: ["sleep", "3600"]