apiVersion: v1
kind: Pod
metadata:
  name: tcp-check
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
      livenessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 15
        periodSeconds: 20
      readinessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 5
        periodSeconds: 10