apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
    tier: web
  ports: 
   - protocol: TCP
     port: 80
     targetPort: 80
  type: LoadBalancer


---
apiVersion: v1
kind: Service
metadata: 
  name: backend-service
spec:
  selector:
    app: backend
    tier: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec: 
  selector:
    app: redis
    tier: cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
      