apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-liveness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-liveness
  template:
    metadata:
      labels:
        app: test-liveness
    spec:
      containers:
        - name: app
          image: busybox
          command: ["sh", "-c", "touch /tmp/healthy && sleep 3600"]
          volumeMounts:
            - name: health
              mountPath: /health
          livenessProbe:
            exec: 
              command: ["sh", "/health/liveness-test.sh"]
            initialDelaySeconds: 3
            periodSeconds: 5

      volumes:
        - name: health
          configMap:
            name: health-config
            items:
              - key: liveness-test.sh
                path: liveness-test.sh
              